### ISSUE TITLE
Error in unimportant Bouncers (BB5) decision

### ISSUE THREAD

**Issue by UncombedCoconut** [TonyGuil/bbchallenge#12]
* Context: https://bbchallenge.org/2706211 is decided by Backward Reasoning anyway, so an error deciding it only harms maniacs like me.
* Tested version: 95af7c40ae8aa12e76e5b6b0fe12827a84c3bece
* Test:
```
$ ./DecideBouncers -X2706211 -T1000000 -S20000 -H1

#2706211: Error at line 307 in BuildVerificationData
```

**Comment by TonyGuil** [comment]
This is because an arbitrary bound on the length of the verification data (500,000 bytes) has been exceeded. I'm not going to spend any time on this, because (i) machine #2706211 is not a bouncer, as the term is understood by my code, and (ii) I am currently working (at a glacial pace, it is true) on reducing the size of the verification data by an order of magnitude. I will keep you posted :-)

**Comment by UncombedCoconut** [comment]
Totally reasonable! I'll close this because it doesn't have to be fixed directly.
