### ISSUE TITLE
Deadly array indexing in HaltingSegment.cpp

### ISSUE THREAD

**Issue by UncombedCoconut** [TonyGuil/bbchallenge#6]
Hi!
One paragraph of context, one paragraph of actual bug report.

Context: Cosmo is doing a writeup of Halting Segment ([WIP](https://cdn.discordapp.com/attachments/1028745685501214740/1056274072423649320/correctness-deciders.pdf)), and asked: [I am not too sure in what direction @TonyGuil goes](https://discord.com/channels/960643023006490684/1028745685501214740/1056285993084403793) (tracing TM execution forward vs backward in time, which starting configurations, etc.). I gestured at your README and tried to provide a trace.
So please feel free to ignore this and chat with Cosmo about whether the paper should describe your implementation in greater detail.

Actual bug report:
There are several lines using `-HalfWidth` and `1 - HalfWidth` as array indexes.
However, `HalfWidth` is a `uint32_t`. I believe relevant language standards say unsigned ints wrap around (so, -HalfWidth is 2³²-HalfWidth), so this attempts to poke a memory address offset 4GB from the intended location.
Locally, it looks like the stupid fix of casting `HalfWidth` to `int64_t` first on these lines is effective. I'm guessing it's preferable to change a few int types in the program, just not sure what's most tasteful and side-effect-free.

**Comment by TonyGuil** [comment]
Hi Justin,
I confess that I never expected anybody to run my code in a 64-bit environment! But I I have changed `HalfWidth` to an `int`, and made a couple of other (small) changes. So I expect it works now -- but I can't test it, because I only have 32-bit capabilities.

But in the process of updating the decider, I realised that my code had got terribly out of synch with my Readme files, going right back to my Cyclers Decider. For instance, I got rid of the two integers in the umf header that you mentioned was causing you some trouble; and the results of my runs are slightly different in some cases. So I am now in the process of re-running everything to make my code self-consistent. I will let you know when I have finished.

As for Halting Segments: I have re-written the search code so that it visits the nodes in exactly the same order as Iijil's Decider. Whether this is forward or backward, I don't know! But my aim was to generate verification data for my wider segment-matching criterion: whenever my code used the wider criterion, I would output the node number and the matched segment. Then a simple modification to Iijil's code could use this information to verify the segment match when it reached the flagged node. But after you posted your [list](http://discuss.bbchallenge.org/t/decider-finite-automata-reduction/123/6?u=tonyg) of Finite Automata Reduction results, I saw that my segment-matching criterion was redundant -- see my [comment](http://discuss.bbchallenge.org/t/decider-finite-automata-reduction/123/7?u=tonyg). So I never finished it.

**Comment by UncombedCoconut** [comment]
Ah, that's helpful/interesting.
Once your docs are as updated as you want, I'll do a trial run with Address Sanitizer / Undefined Behavior Sanitizer; that should help build confidence that the bugs are gone.
We would call Iijil's version (and yours) "backward", meaning each update traces a TM transition backward in time. Your code is credited/described that way in the [paper under construction](https://github.com/bbchallenge/bbchallenge-proofs/blob/main/deciders/correctness-deciders.pdf). I think all is well.

**Comment by TonyGuil** [comment]
I have cleaned up my repository, so feel free to run any tests you like. And I have added a couple of paragraphs to my HaltingSegments README file, which you might like to look at.
